# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

trigger:
- master

pr:
- '*'

variables:
- group: AzureKeyVault
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.0
    inputs:
      version: '3.0.x'
  - task: UseDotNet@2
    displayName: Install .NET Core 2.1
    inputs:
      version: '2.1.x'
  - powershell: ./build.ps1 -ci
    displayName: Invoke build.ps1
    env:
      KEYVAULT_CLIENT_SECRET: $(kv-access-token)
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Windows
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    continueOnError: true
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverlet/reports/Cobertura.xml
  - publish: 'artifacts/'
    artifact: 'Packages'
    displayName: Publish artifacts
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.0
    inputs:
      version: '3.0.x'
  - task: UseDotNet@2
    displayName: Install .NET Core 2.1
    inputs:
      version: '2.1.x'
  - script: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Linux
      testRunner: vstest
      testResultsFiles: '**/*.trx'
